# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "Build"
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    # Random time each week.
    - cron:  '48 7 * * 1'

jobs:
  build:
    uses: silvenga-docker/building/.github/workflows/publish-github.yaml@master
    with:
      no-cache: true
    secrets: inherit
